name: honeypot
description: A Flutter project.
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.0
  material_symbols_icons: ^4.2745.0
  sqflite: ^2.3.3+2
  path: ^1.9.0
  shared_preferences: ^2.5.4
  local_auth: ^2.3.0
  intl: ^0.20.2
  local_auth_android: ^1.0.43
  http: ^1.2.1
  html: ^0.15.4
  url_launcher: ^6.3.0
  external_app_launcher: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "icon.png"
  adaptive_icon_background: "#121212"
  adaptive_icon_foreground: "icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png